### ISSUE TITLE
Issues with Calendar Reminders on Events Page

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/public-website-content#46] opened 2021-04-06 17:39 UTC
We are running into issues downloading (.ics files) on our Intro to Conda registration page. This issues seems to only occur for Windows OS. We need some help identifying the issue.  Another interesting note is the URL includes ical in the name. 

https://www.nih-cfde.org/events/intro-to-conda/
![image](https://user-images.githubusercontent.com/62918474/113753693-3e1fe980-96c3-11eb-9aa9-cb9a2f6a442b.png)

https://www.nih-cfde.org/events/intro-to-conda/ical/

**Comment by josesanchez1815** [comment] 2021-04-06 17:39
This is what we see (Windows Users) when we click on the link.
https://www.nih-cfde.org/events/intro-to-conda/ical/

**Comment by ACharbonneau** [comment] 2021-04-07 14:25
Hey @kloydrti Could you make this a priority to fix please? I'm getting users having problems with both the .ics file on the website and the one that is in the confirmation email.

**Comment by kloydrti** [comment] 2021-04-07 14:49
The text that @josesanchez1815 posted is the contents of the .ics file. On my computer, in any browser, clicking the link automatically downloads that text as the .ics file. The issue is caused by incognito mode. All browsers disable the automatic download in incognito/private windows, so it will only show you the contents of the file. I cannot override this - it is set in the browser. The fix is to right-click on the link and select "save link as". That will let you save the .ics file. 

I will add a note to the link so it will give right-click instructions.

**Comment by josesanchez1815** [comment] 2021-04-07 20:24
Ok. It seems to work as long as I do follow Katy's instructions and type .ics at the end of the file name.

**Comment by ACharbonneau** [comment] 2021-04-07 20:52
Hey @kloydrti I think Jose was in incognito mode, but the people I heard from on helpdesk were not. @josesanchez1815 can you just download *without* right clicking from a normal browser window?

**Comment by josesanchez1815** [comment] 2021-04-07 21:54
I cannot

**Comment by josesanchez1815** [comment] 2021-04-08 16:47
Hello! Just wanted to follow up on some things in regards to this issue. 
So it appears that what prevents my windows computer from downloading the (.ics) file is that Windows cannot parse the ics when there are non-standard punctuation in the file. 

@ACharbonneau and I tested the event  [Pop Up: CFDE Portal Demo](https://www.nih-cfde.org/events/cfde-portal-demo/). We tested the (.ics) link and it didn't work. It generated a page with what looks like the contents of the file (see photo above). The second time we tested the link, Amanda removed the colon from the event title and now it seems I (Windows-User) can left click the link and automatically download the (.ics) file. 

Next steps: I will take out the colons from the event titles to enable windows users to download these files.

**Comment by ACharbonneau** [comment] 2021-04-09 16:10
We tested this even more, and found that some of them with colons actually do work, and Jose couldn't consistently get any link to not work...I'm not sure what is happening, but we are closing this and will make a new issue if we can get repeatable problems in the future

**Closed by ACharbonneau** 2021-04-09 16:10 UTC
Labels: Highest Priority
